### ISSUE TITLE
Failure on specific k8s node: `definitions.h:2:10: fatal error: 'asm/fpu/internal.h' file not found`

### ISSUE THREAD

**Issue by consideRatio** [cryptnono/cryptnono#2]
Hopefully, cryptonono can be setup to be quite robust. At this point, it seems that there is a node on the turing deployment that has some issues though. Looking into it, I found the following logs in one of the four pods, while the other three were fine.

The node where a pod is failing is the youngest, currently `3d5h` old, and by the time the other cryptonono pods had started for the first time, this node wasn't around. I think the 4d15h life could be coupled with when https://github.com/jupyterhub/mybinder.org-deploy/pull/2174 was merged.

```
turing-cryptnono-4zsnh                                    1/1     Running            0          3d10h
turing-cryptnono-cmj7w                                    0/1     CrashLoopBackOff   430        3d5h
turing-cryptnono-fzkj6                                    1/1     Running            0          4d15h
turing-cryptnono-m4gpr                                    1/1     Running            0          4d15h
```

## Erroring pod's container logs

```
$ kubectl logs -n turing turing-cryptnono-cmj7w --container=kubectl-trace-init
+ LSB_FILE=/etc/lsb-release.host
+ OS_RELEASE_FILE=/etc/os-release.host
+ TARGET_DIR=/usr/src
+ HOST_MODULES_DIR=/lib/modules.host
++ uname -r
+ KERNEL_VERSION=5.4.0-1078-azure
+ [[ ! -e /lib/modules/.installed ]]
+ echo 'Headers already installed'
Headers already installed
+ exit 0
```

```
$ kubectl logs -n turing turing-cryptnono-cmj7w --container=trace
definitions.h:2:10: fatal error: 'asm/fpu/internal.h' file not found
```

**Comment by manics** [comment]
Can we close this?

**Comment by consideRatio** [comment]
I think so, not 100% but its better to close and open a new whenever we run into the same issue again I think.
